# Generated by Django 4.2.23 on 2025-08-24 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0003_product_customer_rating_product_demand_forecast_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "forecast_method",
                    models.CharField(default="historical_simulation", max_length=50),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("start_year", models.PositiveIntegerField(default=2020)),
                ("end_year", models.PositiveIntegerField(default=2024)),
                ("forecast_data", models.JSONField(default=list)),
                ("demand_price_curve", models.JSONField(default=list)),
                ("total_forecasted_demand", models.PositiveIntegerField(default=0)),
                ("confidence_score", models.FloatField(default=0.85)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecasts",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product"], name="forecast_de_product_6634ca_idx"
                    ),
                    models.Index(
                        fields=["created_by"], name="forecast_de_created_95350a_idx"
                    ),
                    models.Index(
                        fields=["forecast_method"],
                        name="forecast_de_forecas_669b8e_idx",
                    ),
                ],
            },
        ),
    ]
