# Generated by Django 4.2.23 on 2025-08-23 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("sku", models.CharField(max_length=64, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("stationery", "Stationery"),
                            ("electronics", "Electronics"),
                            ("grocery", "Grocery"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=40,
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "current_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "min_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "max_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("stock_qty", models.PositiveIntegerField(default=0)),
                ("elasticity", models.FloatField(default=1.2)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-updated_at"],},
        ),
        migrations.CreateModel(
            name="ProductPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("new_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="products.product",
                    ),
                ),
            ],
            options={"ordering": ["-changed_at"],},
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="products_pr_sku_ca0cdc_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category"], name="products_pr_categor_14b9c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["owner"], name="products_pr_owner_i_dfa922_idx"),
        ),
    ]
