# Generated by Django 4.2.23 on 2025-08-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="product",
            name="units_sold",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
