# Generated by Django 4.2.23 on 2025-08-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_description_product_units_sold"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="customer_rating",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="demand_forecast",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="optimized_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["demand_forecast"], name="products_pr_demand__f1162b_idx"
            ),
        ),
    ]
