# Generated by Django 4.2.23 on 2025-08-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_userprofile_role_supplierrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
